language: ruby
rvm:
  - 1.9.3
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c 'create database books_multiplier_test' -U postgres
