# encoding: UTF-8
#============================================================================
# Copyright (c) Bureau Pels.  All Rights Reserved.
#============================================================================
development:
  database: books_multiplier_dev
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm

test:
  database: books_multiplier_test
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm

production:
  database: books_multiplier
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm
