development:
  database: books_multiplier_dev
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm

test:
  database: books_multiplier_test
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm

production:
  database: books_multiplier
  adapter: pg
  encoding: utf8
  host: 127.0.0.1
  reconnect: false
  username: books_multiplier
  password: vRkbI7cekowOk3Lm
