# encoding: UTF-8
#============================================================================
# Copyright (c) Bureau Pels.  All Rights Reserved.
#============================================================================
development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  min_messages: ERROR
  database: books_multiplier_dev
  username: books_multiplier
  password: vRkbI7cekowOk3Lm

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  min_messages: ERROR
  database: books_multiplier_test
  username: <%= ENV['TRAVIS'] == 'true' ? 'postgres' : 'books_multiplier' %>
  password: <%= 'vRkbI7cekowOk3Lm' unless ENV['TRAVIS'] == 'true' %>

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  min_messages: ERROR
  database: books_multiplier
  username: books_multiplier
  password: vRkbI7cekowOk3Lm
