development:
  host: localhost
  port: 3000
  protocol: http
  from_email: advidi_dev@localhost
  content_mail: postmaster@localhost
  smtp_settings:
    address: localhost
    enable_starttls_auto: false

test:
  host: localhost
  port: 3000
  protocol: http
  from_email: advidi_test@localhost
  content_mail: postmaster@localhost

production:
  host: localhost
  protocol: https
  from_email: no-reply@hq.rfpels.nl
  content_mail: postmaster@localhost
  smtp_settings:
    address: localhost
    enable_starttls_auto: false

translations:
  application:
    - en
    - nl

googlebooks:
  protocol: 'https'
  host: 'www.googleapis.com'
  path: '/books/v1/volumes'
  query: 'ruby+on+rails'
  start_index: 0
  max_results: 40