--- 
address: 0.0.0.0
onebyone: true
pid: /home/rl/app/shared/pids/thin.pid
port: 9000
timeout: 30
wait: 30
log: /home/rl/app/shared/log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
servers: 4
daemonize: true
chdir: /home/rl/app/current
